title: Our Revolution Alaska
author: Our Revolution Alaska
email: ourrevolutionalaska@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Alaska Our Revolution Chapter

sass:
    style: compressed
